### ISSUE TITLE
panic: json: cannot unmarshal string into Go struct field .main of type bool

### ISSUE THREAD

**Issue by EduardoMartinNube** [DiSiqueira/TinderOnline#11]
Trying to make it work but it crashes.

Is there any line-by-line debugger for Go?

Thanks for this code, now I feel like getting into Go :-)

panic: json: cannot unmarshal string into Go struct field .main of type bool

goroutine 1 [running]:
main.checkError(0x7a07e0, 0xc04225c0f0)
        C:/Go/bin/tinderonline.go:137 +0x51
main.main()
        C:/Go/bin/tinderonline.go:28 +0x161

**Comment by d6o** [comment]
Please see #12
