### ISSUE TITLE
None of my friends show up

### ISSUE THREAD

**Issue by kr1305** [DiSiqueira/TinderOnline#6]
So I've tried to use it, it seems to parse my access code correctly, it displays with my correct name etc but shows none of my friends in the list. Is this a common issue?

**Comment by kr1305** [comment]
Any update on this? Love the tool.

**Comment by AlecAnthonyGarcia** [comment]
@kr1305 In the meantime, you can use https://github.com/CaliAlec/Tinderface

**Comment by kr1305** [comment]
@CaliAlec I don't really know that much about Linux or anything, is there a quick install guide for this?

**Comment by d6o** [comment]
Sorry i am working right now, i will fix this tonight! Some people reported issues with Facebook Permissions over Tinder App, please double check yours, also opt-in in Tinder Social.

**Comment by AlecAnthonyGarcia** [comment]
@kr1305 It's hosted and you can use it directly here: https://tinderface.herokuapp.com/

**Comment by d9vk7x-git** [comment]
I have a similiar issue as the program only shows about 10 of my friends as active.
I know at least two more of my friends who used it in the past couple days and they are not on the list.

**Comment by d6o** [comment]
@CaliAlec Nice to see you here! Your project was a great inspiration to me!!  Thank you for this!

**Comment by d6o** [comment]
@SlimPutin I can only list friends who opted-in for Tinder Social

**Comment by kr1305** [comment]
@DiSiqueira will your app show more than Tinderface or the same?

**Comment by d6o** [comment]
Please see #12
