### ISSUE TITLE
panic: parsing time "-1" as ""2006-01-02T15:04:05Z07:00"": cannot parse "-1" as """

### ISSUE THREAD

**Issue by Saberino** [DiSiqueira/TinderOnline#7]

**Comment by Saberino** [comment]
Thought I'd fixed it - I haven't. As the title. Running latest golang.
e. I suppose the full error would be of use.

panic: parsing time "-1" as ""2006-01-02T15:04:05Z07:00"": cannot parse "-1" as """

goroutine 1 [running]:
main.checkError(0x7b9440, 0xc4201ba870)
        /home/desktop/tinderonline/tinderonline.go:137 +0x4a
main.main()
        /home/desktop/tinderonline/tinderonline.go:28 +0x15a

**Comment by pythonistic** [comment]
In my case, I disallowed access to the birth date and the profile request was unable to parse the returned JSON document.

`"banned":true,"bio":"","birth_date":-1,"can_create_squad":false`

**Comment by jjerphan** [comment]
I got the same problem.
I try to comment the line 28 (`checkError(err)`) but it does not give me anything :
```
Your Profile:
Name: 

|                             Your Friend|                                                      Last Time Online|
|                                        |                                                                      |

```

**Comment by andyxning** [comment]
@Saberino See [golang#9346](https://github.com/golang/go/issues/9346) for more info. I seems that your time format is wrong.

**Comment by d6o** [comment]
Please see #12
