### ISSUE TITLE
-bash: tinderonline: command not found

### ISSUE THREAD

**Issue by abhinayar** [DiSiqueira/TinderOnline#9]
Everything compiles fine till you actually try to run anything, both tinderonline -h as well as the tokenized version.

Best,
A.N.

**Comment by ThomasMW** [comment]
Did you use 'go get' or compile from source.

**Comment by kalebgriepp** [comment]
I used 'go get' and am having the same problem.

**Comment by abhinayar** [comment]
I tried both methods. Finally got it to work with this:

git clone URLTOREPO TinderOnline
cd TinerOnline
go get -v -d
go build *.go
go run tinderonline.go -token=FACEBOOKTOKEN

Hope this helps!

**Comment by kalebgriepp** [comment]
You're a gentleman and a scholar. Worked for me.

**Comment by d6o** [comment]
Please see #12
